server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3307/order_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

  # jpa 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Menu Service gRPC 클라이언트 설정
grpc.client.menu-service.host=localhost
grpc.client.menu-service.port=9090
grpc.client.menu-service.timeout-seconds=2